const USERS_SEARCH_DEFAULT_CAPACITY = 20;
const USERS_SEARCH_DEFAULT_ORDER = 'created';

const ARTICLES_SEARCH_DEFAULT_CAPACITY = 20;
const ARTICLES_SEARCH_DEFAULT_ORDER = 'created';

export {
  USERS_SEARCH_DEFAULT_CAPACITY,
  USERS_SEARCH_DEFAULT_ORDER,
  ARTICLES_SEARCH_DEFAULT_CAPACITY,
  ARTICLES_SEARCH_DEFAULT_ORDER,
};
